### ISSUE TITLE
cernops is not installable from puppetforge

### ISSUE THREAD

**Issue by mhellmic** [cernops/puppet-fetchcrl#2]
Hi,

 we got bug reports from our users, which want to install our puppet modules that rely on fetchcrl. Apparently fetchcrl cannot be installed from the forge.

Here's an excerpt from one:
> We are using puppet 3.4.3.
> (...)
> 
> puppet module install CERNOps-fetchcrl
> Notice: Preparing to install into /etc/puppet/environments/production/modules ...
> Notice: Downloading from https://forge.puppetlabs.com ...
> Notice: Installing -- do not interrupt ...
> Error: No such file or directory -  /etc/puppet/environments/production/modules/fetchcrl/spec/fixtures/modules/fetchcrl/lib
> Error: Try 'puppet help module install' for usage

Installing the fetchcrl module form source then works.

Can you help us with that?

**Comment by bendylan** [comment]
Interestingly couldn't repro with puppet 3.4.3 but more recent puppets complain about symlinks:

Warning: Symlinks in modules are unsupported. Please investigate symlink CERNOps-fetchcrl-0.1.0/spec/fixtures/modules/fetchcrl/templates->../../../../templates.

(Though actually installed ok).

**Comment by andrea-manzi** [comment]
We have reports from sites having the problem reported by Ben, but in this case the installation stops

Warning: Symlinks in modules are unsupported. Please investigate symlink CERNOps-fetchcrl-0.1.0/spec/fixtures/modules/fetchcrl/lib->../../../../lib.
Warning: Symlinks in modules are unsupported. Please investigate symlink CERNOps-fetchcrl-0.1.0/spec/fixtures/modules/fetchcrl/manifests->../../../../manifests.
Warning: Symlinks in modules are unsupported. Please investigate symlink CERNOps-fetchcrl-0.1.0/spec/fixtures/modules/fetchcrl/templates->../../../../templates.
Warning: Symlinks in modules are unsupported. Please investigate symlink CERNOps-fetchcrl-0.1.0/spec/fixtures/modules/fetchcrl/files->../../../../files.
Notice: Installing -- do not interrupt ...
Error: No such file or directory - /etc/puppet/modules/fetchcrl/spec/fixtures/modules/fetchcrl/templates
Error: Try 'puppet help module install' for usage

The OS is SL6 and the version of puppet is 3.7.2

but i cannot reproduce it in the VM installed at CERN with puppet 3.7.4cern3-1

**Comment by bendylan** [comment]
Whether or not we can repro the installation failure (and I've tried but can't) I still think the right thing to do is to remove the symlinks. Unless @traylenator objects I think we'll do that.

**Comment by traylenator** [comment]
symlinks should go, I think of the rspec auto generaters created them.
